[package]
name = "fidlcrs"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = { version = "2.13.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["raw_value", "preserve_order"] }
sha2 = "0.10.9"
